include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    always_declare_return_types: true
    unawaited_futures: true
    avoid_void_async: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    sized_box_for_whitespace: true